Fix send_to_links_buf_crypt malloc() test
Clang found this:
handle.c:277:16: error: address of array 'knet_h->send_to_links_buf_crypt' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
if (!knet_h->send_to_links_buf_crypt) {
~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

We need to test the actual send_to_links_buf_crypt[i] pointer we are
mallocing() and not the array itself.

Signed-off-by: Michele Baldessari <michele@acksyn.org>