Move compiler checks to a macro
Currently we test the validity of compiler macros using CPP.
This breaks clang:
error: unknown warning option '-Wunsigned-char' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wgnu89-inline' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wcpp' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wunused-but-set-variable'; did you mean '-Wunused-const-variable'? [-Werror,-Wunknown-warning-option]

Move to an external macro to test the flags and actually use CC
to test them. Also special care needs to be taken with
format-security and format-nonliteral as they both require
-Wformat to be set for gcc to accept them.

Tested on the following combinations:
- F24 x86_64 - gcc 6.1.1
- F24 x86_64 - clang 3.8.0

Signed-off-by: Michele Baldessari <michele@acksyn.org>